err_max : 0.3
if_debug : 1


target_x : 6.6  
target_y : 0.0  

target_yaw : 0.0
UAV_radius : 0.4
time_final : 40.0
ALPHA : 2.3
MAX_SPEED : 1.0
OBS_EPS : 0.1
KV : -0.15
KN : -0.05
W_goal : 1.0
W_free : 0.0